baseURL = "https://work.jeremybunting.com/"
languageCode = "en-us"
title = "Selected Works from Jeremy Bunting"
theme = "qbunt-portfolio"
[params]
    name = "Selected portfolio projects from technologist Jeremy Bunting"
    googleAnalytics = "UA-6802111-3"
    