---
hide_body: false
fields:
- name: title
  label: Project Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- type: textarea
  name: subhead
  label: Subhead
  description: short description that appears on the landing page
  config:
    wysiwyg: false
- type: select
  name: agency
  config:
    source:
      type: simple
    required: true
    options:
    - Deutsch
    - Spinifex Group
    - HYFN
    - MediaBoom
    - JUXT
    - Calphalon|NewellRubbermaid
  label: Agency
  description: Credited Agency
  default: Deutsch
- type: datetime
  name: launch_date
  label: Launch Date
  config:
    date_format: MM/YYYY
  default: Invalid date
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: text
  name: site_link
  label: Site Link
- type: file
  name: feature_image
  label: Feature Image
- type: image_gallery
  name: gallery
  label: gallery
