---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: select
  name: agency
  config:
    source:
      type: simple
    required: true
    options:
    - Deutsch
    - Spinifex Group
    - HYFN
    - MediaBoom
    - JUXT
    - Calphalon|NewellRubbermaid
  label: Agency
  description: Credited Agency
  default: ''
- type: datetime
  name: project_completed
  label: Project Completed
  description: When this project was completed
  config:
    date_format: MM/YYYY
